# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'airbnb'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'airbnb'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

# This is a HOOK to create the audit_log table at the first dbt run execution 
on-run-start:
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log ( model_name STRING, run_timestamp TIMESTAMP )"

models:
  airbnb:
    #+materialized: incremental #il est possible de definir que tous les modéles de mon projet seront de type incermental 
    #+incremental_strategy: append #ici je definis la strategy d'incrementation
    #+static_analysis: strict. # VERY IMPRTANT : this is for dbt fusion to work correctly
   #This is to grant select on every newly created model to the 2 roles
    +grants:
      select: ["transform", "reporter"]
    #this is another hook to insert a record tracing in the audit_log table each new created model and the time it was created
    +post-hook:
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP)"

    +materialized: view
    dim:
      +materialized: table
    src:
      +materialized: ephemeral

data_tests:
  +store_failures: true
  #if we want a specific schema to be created and used to store tests failure i can specify it here
  +schema: _test_failures
flags:
  require_generic_test_arguments_property: true

vars:
  user_name: Mehdi SI MOHAMMED #This is a DBT variable
  in_test : valeur_existante